{{- if or (and .Values.auth.enabled .Values.auth.token) .Values.electricityMaps.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "green-sarc.secretName" . }}
  labels:
    {{- include "green-sarc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.auth.enabled .Values.auth.token }}
  GREEN_SARC_AUTH_TOKEN: {{ .Values.auth.token | quote }}
  {{- end }}
  {{- if .Values.electricityMaps.apiKey }}
  ELECTRICITYMAPS_API_KEY: {{ .Values.electricityMaps.apiKey | quote }}
  {{- end }}
{{- end }}
